apiVersion: v1
kind: Service
metadata:
  name: mundial2026-service
spec:
  selector:
    app: mundial2026
  ports:
  - port: 8080                             # Puerto del Service dentro del clúster
    targetPort: 8080                          # Puerto del contenedor
    nodePort: 30080                         # Solo para NodePort (rango 30000-32767)
  type: NodePort                            # ClusterIP | NodePort | LoadBalancer